// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://risxaekxhtglfjdjnwqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpc3hhZWt4aHRnbGZqZGpud3F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODkwMTYsImV4cCI6MjA2Mzg2NTAxNn0.SRVpHxPl8XLF5BStyAaOsW417rrpfzkzU7fGMM6cCzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);